---
title: "Selected publications"
---

-   Delabrière A., Gianfrotta G., Dechaumet S., Damont A., Hautbergue T., Roger P., Jamin E.L., Puel O., Junot C., Fenaille F. and Thévenot E.A. (2025) mineMS2: Annotation of spectral libraries with exact fragmentation patterns. *ChemRxiv*, Preprint (<https://doi.org/10.26434/chemrxiv-2025-3c9z1>)

-   Delporte C., Tremblay-Franco M., Guitton Y., Canlet C., Weber R.J.M., Hecht H., Price E.J., Klánová J., Joly C., Dalle C., Saint-Vanne J., Thévenot E., Schmitz I., Chéreau S., Dechaumet S., Diémé B., Giacomoni F., Le Corguillé G., Pétéra M. and Souard F. (2025). Workflow4Metabolomics (W4M): A user-friendly metabolomics platform for analysis of mass spectrometry and nuclear magnetic resonance data. *Current Protocols*, **5**:e70095 (<https://doi.org/10.1002/cpz1.70095>)

<!-- -   Lefebvre T., Eguether T., Thévenot E., Poli A., Chu-Van E., Krasniqi P., Schmitt C., Talbi N., Nicolas G., Puy H., Junot C., Lamazière A., Castelli F., Gouya L. and Fenaille F. (2025) Nontargeted urine metabolomic analysis of acute intermittent porphyria reveals novel interactions between bile acids and heme metabolism: New promising biomarkers for the long-term management of patients. *Journal of Inherited Metabolic Disease*, **48**:1 (<https://doi.org/10.1002/jimd.12809>) -->

-   Karaki D., Dechaumet S., Damont A., Colsch B., Fenaille F., Souloumiac A. and Thévenot E.A. (2024) Non-Negative Matrix Factorization of SWATH DIA Data Improves Global Metabolite Identification. *European Signal Processing Conference (EUSIPCO)*:2387-2391 (<https://doi.org/10.23919/EUSIPCO63174.2024.10715181>)

-   Hajjar G., Barros Santos M.C., Bertrand-Michel J., Canlet C., Castelli F., Creusot N., Dechaumet S., Diémé B., Giacomoni F., Giraudeau P., Guitton Y., Thévenot E., Tremblay-Franco M., Junot C., Jourdan F., Fenaille F., Comte B., Pétriacq P. and Pujos-Guillot E. (2023) Scaling-up metabolomics: Current state and perspectives. *TrAC Trends in Analytical Chemistry*, **167**:117225 (<https://doi.org/10.1016/j.trac.2023.117225>)

<!-- -   Ghazaly C., Biletska K, Thévenot E.A., Devillier P., Naline E., Grassin-Delyle S. and Scorsone E. (2023). Assessment of an e-nose performance for the detection of COVID-19 specific biomarkers. *Journal of Breath Research*, **17**:2 (<https://doi.org/10.1088/1752-7163/acb9b2>) -->

-   Paulhe N., Canlet C., Damont A., Peyriga L., Durand S., Deborde C., Alves S., Bernillon S., Berton T., Bir R., Bouville A., Cahoreau E., Centeno D., Costantino, R., Debrauwer L., Delabrière A., Duperier C., Emery S., Flandin A., Hohenester U., Jacob D., Joly C., Jousse C., Lagree M., Lamari N., Lefebvre M., Lopez-Piffet C., Lyan B., Maucourt M., Migne C., Olivier M.F., Rathahao-Paris E., Petriacq P., Pinelli J., Roch L., Roger P., Roques S., Tabet J.C., Tremblay-Franco M., Traikia M., Warnet A., Zhendre V., Rolin D., Jourdan F., Thévenot E., Moing A., Jamin E., Fenaille F., Junot C., Pujos-Guillot E., and Giacomoni F. (2022). PeakForest: a multi-platform digital infrastructure for interoperable metabolite spectral data and metadata management. *Metabolomics*, **18** (<https://doi.org/10.1007/s11306-022-01899-3>)

-   Roquencourt C., Grassin-Delyle S. and Thévenot, E. A. (2022). ptairMS: real-time processing and analysis of PTR-TOF-MS data for biomarker discovery in exhaled breath. *Bioinformatics*, **38**:1930-1937 (<https://doi.org/10.1093/bioinformatics/btac031>)

-   Imbert A., Rompais M., Selloum M., Castelli F., Mouton-Barbosa E., Brandolini-Bunlon M., Chu-Van E., Joly C., Hirschler A., Roger P., Burger T., Leblanc S., Sorg T., Ouzia S., Vandenbrouck Y., Medigue C., Junot C., Ferro M., Pujos-Guillot E., de Peredo A. G., Fenaille F., Carapito C., Herault Y. and Thévenot, E. A. (2021). ProMetIS, deep phenotyping of mouse models by combined proteomics and metabolomics analysis. *Scientific Data*, **8** (<https://doi.org/10.1038/s41597-021-01095-3>)

-   Comte B., Monnerie S., Brandolini-Bunlon M., Canlet C., Castelli F., Chu-Van E., Colsch B., Fenaille F., Joly C., Jourdan F., Lenuzza N., Lyan B., Martin J., Migné C., Morais J.A., Pétéra M., Poupin N., Vinson F., Thévenot E., Junot C., Gaudreau P. and Pujos-Guillot E (2021). Multiplatform metabolomics for an integrative exploration of metabolic syndrome in older men. *EBioMedicine*, **69** (<https://doi.org/10.1016/j.ebiom.2021.103440>)

-   Grassin-Delyle S., Roquencourt C., Moine P., Saffroy G., Carn S., Heming N., Fleuriet J., Salvator H., Naline E., Couderc L.-J., Devillier P., Thevenot E. A. and Annane D. (2021). Metabolomics of exhaled breath in critically ill COVID-19 patients: A pilot study. *EBioMedicine*, **63** (<https://doi.org/10.1016/j.ebiom.2020.103154>)

-   Stanstrup J., Broeckling C.D., Helmus R., Hoffmann N., Mathe E., Naake T., Nicolotti L., Peters K., Rainer J., Salek R., Schulze T., Schymanski E.L., Stravs M.A., Thévenot E.A., Treutler H., Weber R., Willighagen E., Witting M., Neumann S. (2019). The metaRbolomics toolbox in Bioconductor and beyond. *Metabolites*, **9** (<https://doi.org/10.3390/metabo9100200>)

-   Emami Khoonsari P., Moreno P., Bergmann S., Burman J., Capuccini M., Carone M., Cascante M., de Atauri P., Foguet C., Gonzalez-Beltran A., Hankemeier T., Haug K., He S., Herman S., Johnson D., Kale N., Larsson A., Neumann S., Peters K., Pireddu L., Rocca-Serra P., Roger P., Rueedi R., Ruttkies C., Sadawi N., Salek R.M., Sansone S.A., Schober D., Selivanov V., Thévenot E.A., van Vliet M., Zanetti G., Steinbeck C., Kultima K. and Spjuth O. (2019). Interoperable and scalable data analysis with microservices: applications in metabolomics. *Bioinformatics*, **35**:3752-3760 (<https://doi.org/10.1093/bioinformatics/btz160>)

-   Peters K., Bradbury J., Bergmann S., Capuccini M., Cascante M., de Atauri P., Ebbels T.M.D., Foguet C., Glen R., Gonzalez-Beltran A., Gunther U.L., Handakas E., Hankemeier T., Haug K., Herman S., Holub P., Izzo M., Jacob D., Johnson D., Jourdan F., Kale N., Karaman I., Khalili B., Emami Khonsari P., Kultima K., Lampa S., Larsson A., Ludwig C., Moreno P., Neumann S., Novella J.A., O'Donovan C., Pearce J.T.M., Peluso A., Piras M.E., Pireddu L., Reed M.A.C., Rocca-Serra P., Roger P., Rosato A., Rueedi R., Ruttkies C., Sadawi N., Salek R.M., Sansone S.A., Selivanov V., Spjuth O., Schober D., Thévenot E.A., Tomasoni M., van Rijswijk M., van Vliet M., Viant M.R., Weber R.J.M., Zanetti G. and Steinbeck C. (2019). PhenoMeNal: processing and analysis of metabolomics data in the cloud. *Gigascience*, **8** (<https://doi.org/10.1093/gigascience/giy149>)

-   van Rijswijk M., Beirnaert C., Caron C., Cascante M., Dominguez V., Dunn W., Ebbels T., Giacomoni F., Gonzalez-Beltran A., Hankemeier T., Haug K., Izquierdo-Garcia J., Jimenez R., Jourdan F., Kale N., Klapa M., Kohlbacher O., Koort K., Kultima K., Le Corguille G., Moschonas N., Neumann S., O'Donovan C., Reczko M., Rocca-Serra P., Rosato A., Salek R., Sansone S., Satagopam V., Schober D., Shimmo R., Spicer R., Spjuth O., Thévenot E., Viant M., Weber R., Willighagen E., Zanetti G. and Steinbeck C. (2017). The future of metabolomics in ELIXIR. *F1000Research*, (<https://doi.org/10.12688/f1000research.12342.1>)

-   Delabriere A., Hohenester U.M., Colsch B., Junot C., Fenaille F. and Thévenot E.A. (2017). *proFIA*: a data preprocessing workflow for flow injection analysis coupled to high-resolution mass spectrometry. *Bioinformatics*, **33**:3767-3775 (<https://doi.org/10.1093/bioinformatics/btx458>)

-   Guitton Y., Tremblay-Franco M., Le Corguille G., Martin J.-F., Petera M., Roger-Mele P., Delabriere A., Goulitquer S., Monsoor M., Duperier C., Canlet C., Servien R., Tardivel P., Caron C., Giacomoni F. and Thévenot, E.A. (2017). Create, run, share, publish, and reference your LC-MS, FIA-MS, GC-MS, and NMR data analysis workflows with the Workflow4Metabolomics 3.0 Galaxy online infrastructure for metabolomics. *International Journal of Biochemistry and Cell Biology*, **93**:89-101 (<https://doi.org/10.1016/j.biocel.2017.07.002>)

-   Rinaudo P., Boudah S., Junot C. and Thévenot E.A. (2016). *biosigner*: a new method for the discovery of significant molecular signatures from omics data. *Frontiers in Molecular Biosciences*, **3** (<https://doi.org/10.3389/fmolb.2016.00026>)

-   Giacomoni F., Le Corguille G., Monsoor M., Landi M., Pericard P., Petera M., Duperier C., Tremblay-Franco M., Martin J.-F., Jacob D., Goulitquer S., Thévenot E.A. and Caron C. (2015). Workflow4Metabolomics: A collaborative research infrastructure for computational metabolomics. *Bioinformatics*, **31**:1493-1495 (<https://doi.org/10.1093/bioinformatics/btu813>)

-   Thévenot E.A., Roux A., Xu Y., Ezan E. and Junot C. (2015). Analysis of the human adult urinary metabolome variations with age, body mass index and gender by implementing a comprehensive workflow for univariate and OPLS statistical analyses. *Journal of Proteome Research*, **14**:3322-3335 (<https://doi.org/10.1021/acs.jproteome.5b00354>)

<!-- -   Lenuzza N., Duval X., Nicolas G., Thévenot E., Job S., Videau O., Narjoz C., Loriot M.-A., Beaune P., Becquemont L., Mentre F., Funck-Brentano C., Alavoine L., Arnaud P., Delaforge M. and Benech H. (2016). Safety and pharmacokinetics of the CIME combination of drugs and their metabolites after a single oral dosing in healthy volunteers. *European Journal of Drug Metabolism and Pharmacokinetics*, **41**:125-138 (<https://doi.org/10.1007/s13318-014-0239-0>) -->
